### PR TITLE
Fixed validation condition

### PR DESCRIPTION
**Pull request by vasilake-v**
Fixed validation condition based on the issue #7 reported. 
Restored indent character for lines added before.

### CODE REVIEW

**Review by Nylle — APPROVED** [review]
I'd recommend to wrap indentation changes or other formatting in a separate commit from the actual fix to make reviewing easier next time.

**Review by colesnic89 — APPROVED** [review]

**Comment by slava-v** [comment]
@Nylle , 

sorry, I didn't mean to make any changes to formatting. I am using spaces as indentation character and did not notice there were tabs as indents in file.

I am going to fix this in a next commit

**Comment by slava-v** [comment]
@Nylle , oh... i forgot, this commit, along with other fixes, is reverting previous indentation changes made by me back to tab character (that is used in the project). 

It is, however, conflicting with PSR-2 that states: use 4 spaces as indentation instead of tabs. 
I would suggest adding this in the todo list :)

**Comment by Nylle** [comment]
Hey @slava-v, thanks for your contributions to this project. 

I don't really mind which indentation character is used and how many, as long as the code is still readable. Even mixed is fine for me. Bickering about such minor things just drives people apart. So if you feel it would be better to change these things to follow guidelines, you're welcome to. I don't do PHP anymore so I won't be active here anyway.

Thanks again for your contributions.

**Pull request merged**
